---

# Main task: Benchmark at most once daily, checking if
# the target exists to decide whether to branch or not.

- name: 'Idempotence: Check complete: zoidy_geekbench4'
  stat: path={{ zoidy_geekbench4_results_lnk }}
  register: zoidy_geekbench4_target

- name: Run Benchmark once just once
  include_role:
    name: zoidy_geekbench4
    tasks_from: benchmark
  when: not zoidy_geekbench4_target.stat.exists

