---

- name: Run Benchmark only when specifically requested via --tags
  ansible.builtin.include_role:
    name: zoidy_geekbench4
    tasks_from: benchmark
  tags:
    - never
    - zoidy_geekbench4

