---
# tasks file for zoidy_geekbench4

# 2018-12-13: Developed against Mint 19 ‘Tara’ Ubuntu 18.04.

# [lb]: I'm an Ansible newcomer, and this is the first role
# I've writ! I used https://github.com/pramttl/playbench as
# a starting point, converting it to Galaxy role, updating
# to Geekbench4, and removing all the VM cruft. So basically
# completely different. Nonetheless, a shout-out to parmttl!

- name: Ensure the working directory exists
  file: path={{ zoidy_geekbench4_working_dir }} state=directory

- name: Stat geekbench4 archive before downloading
  stat: path={{ zoidy_geekbench4_working_tar }}
  register: zoidy_geekbench4_archive

- name: Fetch the geekbench4 archive, if necessary
  get_url:
    url: '{{ zoidy_geekbench4_app_downurl }}'
    dest: "{{ zoidy_geekbench4_working_dir }}/"
  # Avoid connecting to the CDN server if the file exists locally.
  # (There's a get_url default, `force: no`, that will not download the
  # archive if it has not changed, but it still checks with the server.)
  when: zoidy_geekbench4_archive.stat.exists == False

- name: Unarchive the geekbench4 archive
  unarchive:
    src: "{{ zoidy_geekbench4_working_tar }}"
    dest: "{{ zoidy_geekbench4_working_dir }}/"
    # We could instead download to the master,
    # and unpack to the host, but we downloaded
    # to the host, so tell Ansible to look there.
    remote_src: yes

- name: Benchmark the host! Run geekbench4
  shell: ./geekbench4
  args:
    chdir: "{{ zoidy_geekbench4_program_dir }}"
  register: geekbench4_output

- set_fact:
    geekbench4_results_url: "{{ geekbench4_output.stdout_lines[-1] | trim }}"

- name: Copy geekbench4 output to geekbench stdout file
  copy: content="{{ geekbench4_results_url }}" dest="{{ zoidy_geekbench4_results_lnk }}"

- name: Tell user where to find geekbench4 results
  debug:
    msg: >
          You'll find the geekbench4 results here!

            {{ geekbench4_results_url }}

- name: Open geekbench4 results in browser window locally
  local_action: command sensible-browser {{ geekbench4_results_url }}

