---

# The author's convention is to dispatch tasks, even when there's only one.
# - Hence this file might appear somewhat pointless.

- name: Run Geekbench 4 benchmark task
  ansible.builtin.include_role:
    name: zoidy_geekbench4
    tasks_from: benchmark
    apply: { tags: always }
  tags: benchmark

